# Generated by Django 5.0.6 on 2024-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.CharField(choices=[('0', 'Ceibos'), ('1', 'Entre_Rios'), ('2', 'CCT_terrestre'), ('3', 'Entregado'), ('4', 'Paseo_Shopping_Machala')], default='Ceibos', max_length=20),
        ),
    ]
