# Generated by Django 5.0.6 on 2024-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
