# Generated by Django 5.0.6 on 2024-08-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_alter_client_cellphone_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
