# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-tests:
    name: Run Angular Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    - name: Run tests
      run: |
        cd frontend
        npm run test:ci
        
  backend-tests:
    name: Run Django Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0  
        env:
          MYSQL_ROOT_PASSWORD: ''  
          MYSQL_DATABASE: database_nintventario
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
    
    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping --host=127.0.0.1 --port=3306 --silent; do
          echo 'Waiting for MySQL...'
          sleep 2
        done
        
    - name: Run migrations
      run: |
        python backend/manage.py migrate

    - name: Run tests
      run: |
        python backend/manage.py test

